import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// app/layout.tsx or wherever you use ThemeProvider
import { ThemeProvider } from "@/components/ui/theme-provider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <main className="min-h-screen">{children}</main>
            {/* footer */}
            <footer>
              <div>
                <p>Made with Love and Coffee!</p>
              </div>
            </footer>
          </ThemeProvider>
      </body>
    </html>
  );
}
